setwd("/Users/virsingh/Downloads")
power<-read.table("household_power_consumption.txt", sep=";",header=TRUE,na.string="?")
power$Date_formatted<-as.Date(power$Date,"%d/%m/%Y")
power_range<-subset(power,power$Date_formatted>=as.Date("2007-02-01") & power$Date_formatted<=as.Date("2007-02-02"))
power_range$Date_Time<-strptime(paste(power_range$Date,power_range$Time),"%d/%m/%Y %H:%M:%S")
par(mar=c(8,6,2,2))
with(power_range,plot(Date_Time,Global_active_power,type='l',ylab="Global Active Power(kilowatts)",xlab=""))
dev.copy(png,"plot2.png",height=480,width=480)
dev.off()
